#include "shaders.h"
/*
 * This file was automatically generated by the gl-to-cpp.sh script
 * using the opengl shading language files in the 'shaders' directory
 * in the root of this project.
 *
 * Please modify these files then re-generate this file by running
 * the gl-to-cpp.sh script.
 *
 * Generated on  'Sun Mar 15 03:14:43 AM EDT 2026'  using  '../shaders/gl-to-cpp.sh ../shaders'
 */
 
const char* Shaders::shader_post_vertex = 
"/network/Programming/oglopp-skel/shaders/post/vertex.glsl\0";

const char* Shaders::shader_post_fragment = 
"/network/Programming/oglopp-skel/shaders/post/fragment.glsl\0";

const char* Shaders::shader_view_vertex = 
"/network/Programming/oglopp-skel/shaders/view/vertex.glsl\0";

const char* Shaders::shader_view_geometry = 
"/network/Programming/oglopp-skel/shaders/view/geometry.glsl\0";

const char* Shaders::shader_view_fragment = 
"/network/Programming/oglopp-skel/shaders/view/fragment.glsl\0";

