#!/bin/env bash

# ./shaders/gl-to-cpp.sh
# Segmentation fault         (core dumped) ./shaders/gl-to-cpp.sh
#
# How tf

SHADERPATH="$(dirname "$0")"
RUNTIMEPATH="$@"
SOURCE="$SHADERPATH/../src/shaders.cpp"
HEADER="$SHADERPATH/../include/shaders.h"

MODE="FILE"
if [ -z "$RUNTIMEPATH" ] ; then
	MODE="RAW"
elif [ -d "$RUNTIMEPATH" ] ; then
	# Normalize the runtime path static if it's an existing directory
	WD=$PWD
	cd "$RUNTIMEPATH"
	RUNTIMEPATH=$PWD
	cd "$WD"
fi



# PREDEFINED
INFO="
/*
 * This file was automatically generated by the gl-to-cpp.sh script
 * using the opengl shading language files in the 'shaders' directory
 * in the root of this project.
 *
 * Please modify these files then re-generate this file by running
 * the gl-to-cpp.sh script.
 *
 * Generated on  '$(date)'  using  '$0 $@'
 */
 "

SRC_PREFIX="#include \"shaders.h\"$INFO"
HDR_PREFIX="#ifndef SHADERS_H
#define SHADERS_H

#include <oglopp/shader.h>
using namespace oglopp;
$INFO
class Shaders {
private:"
HDR_SUFFIX="\t{}\n};\n#endif // SHADERS_H"


# CONSTRUCTION
HDR_VARS=""
HDR_OBJS=""
HDR_CONSTRUCT=""


echo "$SRC_PREFIX" > "$SOURCE"

# For every directory in 'shaders'...
for dir in $(ls $SHADERPATH); do
	DIR="$SHADERPATH/$dir"
	if [ ! -d "$DIR" ] ; then continue ; fi
	if [ -z "$HDR_CONSTRUCT" ] ; then
		HDR_CONSTRUCT="$HDR_CONSTRUCT:\n"
	else
		HDR_CONSTRUCT="$HDR_CONSTRUCT,\n"
	fi

	HDR_OBJS="$HDR_OBJS\tShader $dir;\n"
	HDR_CONSTRUCT="$HDR_CONSTRUCT\t$dir(\n"

	# For every glsl file in each subdirectory...
	# | sort | tac to sort anti-alphabetically (vertex, geometry, fragment) (I love it when luck simplifies the design)
	for file in $(ls "$DIR" | sort | tac | grep -Eo "^[^\.]+") ; do
		FILE="$DIR/$file.glsl"
		if [ ! -f "$FILE" ] ; then continue ; fi

		# Write to the shaders cpp file
		echo -en "const char* Shaders::shader_${dir}_$file = \n\"" >> "$SOURCE"

		HDR_CONSTRUCT="$HDR_CONSTRUCT\t\tshader_${dir}_$file,\n"
		HDR_VARS="$HDR_VARS\tstatic const char* shader_${dir}_$file;\n"

		# Write the actual shader line by line
		if [ "$MODE" = "RAW" ] ; then
			while IFS= read -r line ; do
				echo "$line\n\\" >> "$SOURCE"
				#echo -n "$line\n" >> "$SOURCE"
			done < "$FILE"
		else
			echo -n "$RUNTIMEPATH/$dir/$file.glsl" >> "$SOURCE"
		fi


		echo -e "\\\\0\";\n" >> "$SOURCE"
	done

	HDR_VARS="$HDR_VARS\n"
	HDR_CONSTRUCT="$HDR_CONSTRUCT\t\tShaderType::$MODE\n\t)"
done

echo -e "$HDR_PREFIX
${HDR_VARS}public:
$HDR_OBJS
	inline Shaders() $HDR_CONSTRUCT
$HDR_SUFFIX" > "$HEADER"
