#ifndef SHADERS_H
#define SHADERS_H

#include <oglopp/shader.h>
using namespace oglopp;

/*
 * This file was automatically generated by the gl-to-cpp.sh script
 * using the opengl shading language files in the 'shaders' directory
 * in the root of this project.
 *
 * Please modify these files then re-generate this file by running
 * the gl-to-cpp.sh script.
 *
 * Generated on  'Sun Mar 15 03:14:43 AM EDT 2026'  using  '../shaders/gl-to-cpp.sh ../shaders'
 */
 
class Shaders {
private:
	static const char* shader_post_vertex;
	static const char* shader_post_fragment;

	static const char* shader_view_vertex;
	static const char* shader_view_geometry;
	static const char* shader_view_fragment;

public:
	Shader post;
	Shader view;

	inline Shaders() :
	post(
		shader_post_vertex,
		shader_post_fragment,
		ShaderType::FILE
	),
	view(
		shader_view_vertex,
		shader_view_geometry,
		shader_view_fragment,
		ShaderType::FILE
	)
	{}
};
#endif // SHADERS_H
